# Generated by Django 4.2.16 on 2025-01-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking_Data_Ingestion_System', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
